ci: fix error BUILD ERROR projects/truly-ui/src/components/schedule/views/day/view-day.component.html(19,12): : Property 'lastIndex' does not exist on type 'ViewDayComponent'.